services:
  app:
    image: jmix-ai-backend
    environment:
      - JAVA_OPTS=-XX:MaxMetaspaceSize=512m -Xmx2g
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TRAININGS_LOCAL_PATH=/app/trainings
    ports:
      - "8081:8081"
    volumes:
      - ${TRAININGS_REPO_PATH}:/app/trainings
    networks:
      - jmix-ai-network
    depends_on:
      - postgres
      - pgvector
      - reranker

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=jmix-ai-backend
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - jmix-ai-network

  pgvector:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgvector-data:/var/lib/postgresql/data
    networks:
      - jmix-ai-network

  reranker:
    image: jmix-ai-reranker
    networks:
      - jmix-ai-network

networks:
  jmix-ai-network:
    external: true

volumes:
  postgres-data:
  pgvector-data: