services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    ports:
      - "4318:4318"
    volumes:
      - ./otelcol-config.yaml:/config.yaml
    command:
      - --config=file:/config.yaml
    networks:
      - jmix-ai-network

  loki:
    image: grafana/loki
    networks:
      - jmix-ai-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - jmix-ai-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    networks:
      - jmix-ai-network
    depends_on:
      - prometheus
      - loki

volumes:
  grafana-storage:

networks:
  jmix-ai-network:
    external: true
